### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by miklb** [hurricane-response/response-theme#2]
Code for America has a brilliant style guide https://style.codeforamerica.org 

However as a branding element, my understanding is it should only be used for the main CFA site. 

As this project is multi-brigade and under CFA, would it make sense to maintain the visual identity on the map site and any landing sites, or a more unique look?

Currently the map site uses bulma.io for default styling with a few overrides.

**Comment by tdooner** [comment]
A couple things:

* The current CfA marketing style guide URL is https://v4.style.codeforamerica.org/ but we are working on a v5 right now because... v4 is a very kind of special.
* There is a second style guide which is probably closer to the use case for the API: https://cfa-styleguide.herokuapp.com/cfa/styleguide (repo is codeforamerica/cfa-styleguide-gem) and it can be easily re-used in Rails projects
* Generally, love the idea. I'd lean towards the second option.

**Comment by miklb** [comment]
This isn’t the API so much as the map site, but I dig the other style guide too.

**Comment by miklb** [comment]
Decided on no style guide but we are using the colors from that guide
